# Generated by Django 5.0.6 on 2024-07-06 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
